services:

  polymath:
    container_name: polymath
    build: .
    command: python -u run
    restart: always
    volumes:
      - /data/polymath:/polymath/polymath/storage

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'atlas.lukehemmin.com'
      SITES: 'atlas.lukehemmin.com=polymath:8080'
      FORCE_HTTPS: "false"

volumes:
  ssl_data:
